[general]
email = ""

[server]
headless = true
enableCORS = false
port = 8501
maxUploadSize = 10

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[client]
caching = true
displayEnabled = true
showErrorDetails = false
