# Streamlit secrets for deployment
# Rename this file to "secrets.toml" and add your actual values

[general]
environment = "production"  # or "development"

[database]
# Add database credentials if needed
# host = "your-db-host"
# username = "your-username"
# password = "your-password"

[api]
# Add API keys if needed
# openai_api_key = "your-api-key"
# google_api_key = "your-google-api-key"

[deployment]
app_name = "regression-simulator"
version = "1.0.0"
maintainer = "Arendra"
contact_email = "arendra6268@gmail.com"
